In [17]:
def homework(*messages):
    print(" >> ", " ".join(str(message) for message in messages))

In [4]:
import numpy as np
temperature = [20.1, 20.1, 20.2, 20.4]
print(temperature)

t1 = temperature * 5

print(f"При множенні на 5 маємо: {t1}")
homework("Чому маємо такий результат?")
homework("because multiplying a number by a dictionary, list, tuple, or string completes it a specified number of times")

t1 = [ x*5 for x in temperature] 
print(f"Тепер отримаємо: {t1}") 
homework("Чому тепер множення успішне?")
homework("Because we multiplied each of the elements of the list, not the list itself")

t2 = np.array(temperature)
print("Масив з використанням методів NumPy", t2)

t3 = t2 * 5
print("При множенні на 5 отримуємо:", t3)

[20.1, 20.1, 20.2, 20.4]
При множенні на 5 маємо: [20.1, 20.1, 20.2, 20.4, 20.1, 20.1, 20.2, 20.4, 20.1, 20.1, 20.2, 20.4, 20.1, 20.1, 20.2, 20.4, 20.1, 20.1, 20.2, 20.4]

>>>>> Чому маємо такий результат? 

because multiplying a number by a dictionary, list, tuple, or string completes it a specified number of times
Тепер отримаємо: [100.5, 100.5, 101.0, 102.0]

>>>>> Чому тепер множення успішне? 

Because we multiplied each of the elements of the list, not the list itself
Масив з використанням методів NumPy [20.1 20.1 20.2 20.4]
При множенні на 5 отримуємо: [100.5 100.5 101.  102. ]


In [5]:
print("Все можна сторити ручну за допомогою методу np.array передавши йому набір значень у вигляді List:")
vector_row = np.array([[1, -5, 3, 2, 4]])
vector_column = np.array([[1], 
                          [2], 
                          [3], 
                          [4]])
print(vector_row, "\nВектор має розмір", vector_row.shape)
print(vector_column, "\nВектор має розмір", vector_column.shape)

Все можна сторити ручну за допомогою методу np.array передавши йому набір значень у вигляді List:
[[ 1 -5  3  2  4]] 
Вектор має розмір (1, 5)
[[1]
 [2]
 [3]
 [4]] 
Вектор має розмір (4, 1)


In [18]:
start = 5
size_of_vec = 100
x = range(size_of_vec)
a = np.arange(size_of_vec)
print(f"Масив згенерований простим range: {x[0:5]} та методом arange: {a[0:5]}")
homework("Виведіть весь діапазон чисел.")
homework(list(x))

a = np.arange(start, size_of_vec)
print(f"Можемо задавати початок генерації вектора, перший елемент: {a[0]}")
homework("Виведіть останній діапазон в згенерованому масиві.")
homework(a[-1])

x = range(start, size_of_vec)
print("Те саме але з вбудованою функцією range:", x)
print("Власне вивід значень:", list(x)[0], )
homework("Виведіть якесь число з середини діапазону.")
middle_value = list(x)[(len(list(x)) // 2)]
homework("A number from the middle of the range:", middle_value)

x = np.arange(10.4)
print("Будем мати:", x)
x = np.arange(0.5, 4, 0.5)
print("З кроком 0.5:", x)
x = np.arange(0.04, 1.84, 0.08)
print("З кроком 0.08:", x, "\n Зерніть уагу на заокруглення")
homework("Згенеруйте значення де крок буде мати чотири нулі після коми, яким буде результат?")
y = np.arange(0.0001, 1.8401, 0.0001)
homework(y)


y = x * 2.5
print("Після перемноження:", y)
homework("Піднесіть отримане число до степеня та поділіть на 0.4 - Яким буде результат?")
result = (y ** 2) / 0.4
homework("Exponentiation to a second power and division by 0.4:", result)


Масив згенерований простим range: range(0, 5) та методом arange: [0 1 2 3 4]
 >>  Виведіть весь діапазон чисел.
 >>  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
Можемо задавати початок генерації вектора, перший елемент: 5
 >>  Виведіть останній діапазон в згенерованому масиві.
 >>  99
Те саме але з вбудованою функцією range: range(5, 100)
Власне вивід значень: 5
 >>  Виведіть якесь число з середини діапазону.
 >>  A number from the middle of the range: 52
Будем мати: [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
З кроком 0.5: [0.5 1.  1.5 2.  2.5 3.  3.5]
З кроком 0.08: [0.04 0.12 0.2  0.28 0.36 0.44 0.52 0.6  0.68 0.76 0.84 0.92 1.   1.08
 1.16

In [19]:
a = np.linspace(start, size_of_vec)
print(f"Згенерували {len(a)} чисел в діапазоні {a[0]} до {a[-1]}")
#print(f"Власне числа: {a}")
homework("Виведіть кожне друге число згенерованого діапазону. Тут будее потрібен цикл :)")
for i in range(0, len(a), 2):
    homework(a[i])

print("Можна зменшити кількість чисел до 5:")
a = np.linspace(start, size_of_vec, 5)
print(a)
homework("Збільшіть кількість чисел до 100. Виведіть перших та останніх 10.")
a = np.linspace(start, size_of_vec, 100)
homework("First 10 numbers:", a[:10])
homework("Last 10 numbers:", a[-10:])


print("""Як бачимо перше та останнє значення завжди входять у згенерований діапазон. 
Відповідно при цьому вираховується крок.
Це можна змінити, виключивши останнє значення з визначення діапазону.
""")

print(np.linspace(start, size_of_vec, 5, endpoint=False))
homework("Спробуйте самі порахуавти крок.")
step = (size_of_vec - start) / (5 - 1)
homework(f"Calculated step: {step}")


_, sp_1 = np.linspace(start, size_of_vec, 5, endpoint=True, retstep=True)
_, sp_2 = np.linspace(start, size_of_vec, 5, endpoint=False, retstep=True)
print(f"Для порівняння, ми можемо визначити крок автоматично, у нашому випадку це {sp_1} та {sp_2}")
homework("Чому маємо такий крок?")
homework("When `endpoint=True`, the step is smaller because the last value is included.", "When `endpoint=False`, the step is larger because the last value is excluded.")


Згенерували 50 чисел в діапазоні 5.0 до 100.0
 >>  Виведіть кожне друге число згенерованого діапазону. Тут будее потрібен цикл :)
 >>  5.0
 >>  8.877551020408163
 >>  12.755102040816325
 >>  16.632653061224488
 >>  20.51020408163265
 >>  24.387755102040817
 >>  28.26530612244898
 >>  32.14285714285714
 >>  36.0204081632653
 >>  39.89795918367347
 >>  43.775510204081634
 >>  47.6530612244898
 >>  51.53061224489796
 >>  55.40816326530612
 >>  59.285714285714285
 >>  63.16326530612245
 >>  67.0408163265306
 >>  70.91836734693878
 >>  74.79591836734694
 >>  78.6734693877551
 >>  82.55102040816327
 >>  86.42857142857143
 >>  90.3061224489796
 >>  94.18367346938776
 >>  98.06122448979592
Можна зменшити кількість чисел до 5:
[  5.    28.75  52.5   76.25 100.  ]
 >>  Збільшіть кількість чисел до 100. Виведіть перших та останніх 10.
 >>  First 10 numbers: [ 5.          5.95959596  6.91919192  7.87878788  8.83838384  9.7979798
 10.75757576 11.71717172 12.67676768 13.63636364]
 >>  Last 10 number

In [ ]:
examples = {
    'Скаляр': np.array(1), 
    'Вектор Рядок': np.array([1, 2, 3]), 
    'Вектор Стовпець': np.array([[1], [2], [3]]), 
    'Матриця': np.array([[1, 2],[3, 4], [5, 6]]),
    'Багатовимірна Матриця': np.array([ [[111, 112], [121, 122]],
                                        [[211, 212], [221, 222]],
                                        [[311, 312], [321, 322]] ])
    }
for key in examples:
    print(f"Розглядаємо приклад з {key}. \nЗначення x буде: \n", examples[key])
    print(f"Тип {key} x: ", type(examples[key]))
    print(f"Розмірність/вимір {key} x:", np.ndim(examples[key]))
    print(f"Форма {key} x: ", examples[key].shape)
    print(f"Кількість елементів х: {np.size(examples[key])}")
    print("-=-"*10)

homework("""Як Ви думаєте чому маємо такий результат для функції np.ndim (Розмірність/вимір/dimension).
Чому значення для векторів та матриць однакове та не співпдає з значенням shape?
Задайте власні вектори з різними числами.""")
homework("np.ndim` gives the number of dimensions. Vectors and matrices can match because column vectors are 2D. `Shape` shows the size along each axis.")



Розглядаємо приклад з Скаляр. 
Значення x буде: 
 1
Тип Скаляр x:  <class 'numpy.ndarray'>
Розмірність/вимір Скаляр x: 0
Форма Скаляр x:  ()
Кількість елементів х: 1
-=--=--=--=--=--=--=--=--=--=-
Розглядаємо приклад з Вектор Рядок. 
Значення x буде: 
 [1 2 3]
Тип Вектор Рядок x:  <class 'numpy.ndarray'>
Розмірність/вимір Вектор Рядок x: 1
Форма Вектор Рядок x:  (3,)
Кількість елементів х: 3
-=--=--=--=--=--=--=--=--=--=-
Розглядаємо приклад з Вектор Стовпець. 
Значення x буде: 
 [[1]
 [2]
 [3]]
Тип Вектор Стовпець x:  <class 'numpy.ndarray'>
Розмірність/вимір Вектор Стовпець x: 2
Форма Вектор Стовпець x:  (3, 1)
Кількість елементів х: 3
-=--=--=--=--=--=--=--=--=--=-
Розглядаємо приклад з Матриця. 
Значення x буде: 
 [[1 2]
 [3 4]
 [5 6]]
Тип Матриця x:  <class 'numpy.ndarray'>
Розмірність/вимір Матриця x: 2
Форма Матриця x:  (3, 2)
Кількість елементів х: 6
-=--=--=--=--=--=--=--=--=--=-
Розглядаємо приклад з Багатовимірна Матриця. 
Значення x буде: 
 [[[111 112]
  [121 122]]

 [[211 

An attempt to understand how large-scale matrices are organised

In [ ]:
homework(f"Створіть власні масиви з різною кількістю елементів та використайте метод shape для визначення їх вимірів.")


In [27]:
matrix3 = np.random.rand(3, 3, 3)
matrix4 = np.random.rand(2, 3, 1, 2)
matrix5 = np.random.rand(1, 1, 1, 1, 1)
print(matrix3)
print(matrix5)
print(matrix4)

[[[0.70170608 0.39116124 0.31915567]
  [0.54244773 0.80960346 0.94137489]
  [0.73449071 0.17211768 0.48708049]]

 [[0.8130651  0.06619065 0.94104671]
  [0.07387085 0.80282911 0.46752963]
  [0.58086041 0.00490842 0.50616455]]

 [[0.65266364 0.36161706 0.88900076]
  [0.88217115 0.9575759  0.24298483]
  [0.92273076 0.15997763 0.09919428]]]
[[[[[0.24415299]]]]]
[[[[0.29364237 0.13396042]]

  [[0.01398272 0.40661408]]

  [[0.75239987 0.20947456]]]


 [[[0.22617713 0.62782518]]

  [[0.89277941 0.76984466]]

  [[0.30057536 0.80361449]]]]


In [31]:
homework("Попрактикуйтесь доступатись до елементів, виведіть декілька елементів різними способами.")

print_shape = lambda matrix: homework(f"Shape of matrix: {'x'.join(map(str, matrix.shape))}")

homework("Matrix 3:")
homework(matrix3)
print_shape(matrix3)
homework("Element at position [0, 1, 2]:")
homework(matrix3[0, 1, 2])
homework("All elements from the first layer:")
homework(matrix3[0])
homework("First row of the second layer:")
homework(matrix3[1, 0])

homework("\nMatrix 4:")
homework(matrix4)
print_shape(matrix4)
homework("Element at position [1, 2, 0, 1]:")
homework(matrix4[1, 2, 0, 1])
homework("Elements from the second layer for the first and second dimensions:")
homework(matrix4[1, :, 0, :])

homework("\nMatrix 5:")
homework(matrix5)
print_shape(matrix5)
homework("Number of elements in matrix5:")
homework(np.size(matrix5))





 >>  Попрактикуйтесь доступатись до елементів, виведіть декілька елементів різними способами.
 >>  Matrix 3:
 >>  [[[0.70170608 0.39116124 0.31915567]
  [0.54244773 0.80960346 0.94137489]
  [0.73449071 0.17211768 0.48708049]]

 [[0.8130651  0.06619065 0.94104671]
  [0.07387085 0.80282911 0.46752963]
  [0.58086041 0.00490842 0.50616455]]

 [[0.65266364 0.36161706 0.88900076]
  [0.88217115 0.9575759  0.24298483]
  [0.92273076 0.15997763 0.09919428]]]
 >>  Shape of matrix: 3x3x3
 >>  Element at position [0, 1, 2]:
 >>  0.9413748907375498
 >>  All elements from the first layer:
 >>  [[0.70170608 0.39116124 0.31915567]
 [0.54244773 0.80960346 0.94137489]
 [0.73449071 0.17211768 0.48708049]]
 >>  First row of the second layer:
 >>  [0.8130651  0.06619065 0.94104671]
 >>  
Matrix 4:
 >>  [[[[0.29364237 0.13396042]]

  [[0.01398272 0.40661408]]

  [[0.75239987 0.20947456]]]


 [[[0.22617713 0.62782518]]

  [[0.89277941 0.76984466]]

  [[0.30057536 0.80361449]]]]
 >>  Shape of matrix: 2x3x1x2
 

In [35]:
A = np.array([ [3.4, 8.7, 9.9], 
               [1.1, -7.8, -0.7],
               [4.1, 12.3, 4.8],
               [7.0, -3.9, 5.1]])
homework("Попрактикуйтесь в доступі до багатовимірного масиву, виведіть елементів які належать діагоналі.")
for i in range(min(A.shape)):  
    homework(A[i, i])  

 >>  Попрактикуйтесь в доступі до багатовимірного масиву, виведіть елементів які належать діагоналі.
 >>  3.4
 >>  -7.8
 >>  4.8


In [34]:
S = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
homework("Попрактикуйтесь у витягуванні елементів, візьміть 4 значення з кінця масиву.")
homework(S[-4:])

 >>  Попрактикуйтесь у витягуванні елементів, візьміть 4 значення з кінця масиву.
 >>  [6 7 8 9]


In [36]:
A = np.array([
[11, 12, 13, 14, 15],
[21, 22, 23, 24, 25],
[31, 32, 33, 34, 35],
[41, 42, 43, 44, 45],
[51, 52, 53, 54, 55]])
homework("Попрактикуйтесь у витягуванні елементів, візьміть матрицю 2х2 з нижнього та верхнього кутка матриці А.")
top_left = A[:2, :2]  
bottom_right = A[-2:, -2:]
homework(f"Top-left 2x2 submatrix:\n{top_left}")
homework(f"Bottom_right 2x2 submatrix:\n{bottom_right}")


 >>  Попрактикуйтесь у витягуванні елементів, візьміть матрицю 2х2 з нижнього та верхнього кутка матриці А.
 >>  Top-left 2x2 submatrix:
[[11 12]
 [21 22]]
 >>  Bottom_right 2x2 submatrix:
[[44 45]
 [54 55]]


In [40]:
A = np.arange(28).reshape(4, 7)

homework("Попрактикуйтесь у витягуванні елементів, будь-яка робоча комбінація.")
print(A)
homework(f"Every second element from index 6 in the first row: {A[0, 6::2]}")
homework(f"Every third element from index 9 in the first row: {A[0, 9::3]}")
homework(f"Starting from index 6, every third element in the first row: {A[0, 6::3]}")
homework(f"Rows with index 6 and 9: {A[::6, ::]}")
homework(f"2x2 submatrix starting from (6,6) to (9,9): {A[6:8, 6:8]}")
homework(f"2x2 submatrix from (6,6) with step 2: {A[6::2, 6::2]}")
homework(f"Second and fourth row (indices 6 and 9): {A[::3, :]}")
homework(f"Last 3 elements starting from index 6: {A[:, 6:9]}")
homework(f"Reversed rows and columns, including elements with indices 6 and 9: {A[::-1, ::-1]}")


 >>  Попрактикуйтесь у витягуванні елементів, будь-яка робоча комбінація.
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]]
 >>  Every second element from index 6 in the first row: [6]
 >>  Every third element from index 9 in the first row: []
 >>  Starting from index 6, every third element in the first row: [6]
 >>  Rows with index 6 and 9: [[0 1 2 3 4 5 6]]
 >>  2x2 submatrix starting from (6,6) to (9,9): []
 >>  2x2 submatrix from (6,6) with step 2: []
 >>  Second and fourth row (indices 6 and 9): [[ 0  1  2  3  4  5  6]
 [21 22 23 24 25 26 27]]
 >>  Last 3 elements starting from index 6: [[ 6]
 [13]
 [20]
 [27]]
 >>  Reversed rows and columns, including elements with indices 6 and 9: [[27 26 25 24 23 22 21]
 [20 19 18 17 16 15 14]
 [13 12 11 10  9  8  7]
 [ 6  5  4  3  2  1  0]]


In [ ]:
A = np.arange(50)
homework("Виведіть всі непарні числа з даного масиву.")
homework(f"All odd numbers in the array: {A[A % 2 != 0]}")

 >>  Виведіть всі непарні числа з даного масиву.
 >>  All odd numbers in the array: [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]
 >>  All odd numbers in the array: [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]
