In [2]:
def homework(*messages):
    print(" >> ", " ".join(str(message) for message in messages))
import numpy as np
import os

In [ ]:
l = (3, 3)

O = np.ones(l)
R = np.random.random(l)
Z = np.zeros(l)
C = np.arange(l[0])
print(f"""
Віднімання:\n {C - (O + 10)}
Множення:\n {O * R}
Ділення:\n {R / C}
Степінь:\n {C ** Z}
Поріняння:\n {R > 0.5}
Ділення на 0:\n {O / Z}
""")



Віднімання:
 [[-11. -10.  -9.]
 [-11. -10.  -9.]
 [-11. -10.  -9.]]
Множення:
 [[0.91332473 0.26128917 0.35157287]
 [0.847404   0.95592338 0.95052303]
 [0.68008323 0.88135735 0.08046401]]
Ділення:
 [[       inf 0.26128917 0.17578644]
 [       inf 0.95592338 0.47526152]
 [       inf 0.88135735 0.040232  ]]
Степінь:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Поріняння:
 [[ True False False]
 [ True  True  True]
 [ True  True False]]
Ділення на 0:
 [[inf inf inf]
 [inf inf inf]
 [inf inf inf]]

 >>  
- Створіть власну матрицю за допомогою методу eye та виконайте порівняння на наявність 1.
- Створіть матрицю ones та відніміть від неї матрицю eye (щоб у результаті вийшла матриця де цетнтральні діагональ все нулі).

 >>  [[ True False False False False False]
 [False  True False False False False]
 [False False  True False False False]
 [False False False  True False False]
 [False False False False  True False]
 [False False False False False  True]]
 >>  [[0. 1. 1. 1. 1. 1.]
 [1. 0. 1. 1. 1. 1

C:\Users\kastr\AppData\Local\Temp\ipykernel_17436\2895400233.py:10: RuntimeWarning: divide by zero encountered in divide
  Ділення:\n {R / C}
C:\Users\kastr\AppData\Local\Temp\ipykernel_17436\2895400233.py:13: RuntimeWarning: divide by zero encountered in divide
  Ділення на 0:\n {O / Z}


In [32]:
homework("""
- Створіть власну матрицю за допомогою методу eye та виконайте порівняння на наявність 1.
- Створіть матрицю ones та відніміть від неї матрицю eye (щоб у результаті вийшла матриця де цетнтральні діагональ все нулі).
""")
K = np.eye(6)
ones = np.ones(6)
homework(K == 1)
homework(ones-K)


 >>  
- Створіть власну матрицю за допомогою методу eye та виконайте порівняння на наявність 1.
- Створіть матрицю ones та відніміть від неї матрицю eye (щоб у результаті вийшла матриця де цетнтральні діагональ все нулі).

 >>  [[ True False False False False False]
 [False  True False False False False]
 [False False  True False False False]
 [False False False  True False False]
 [False False False False  True False]
 [False False False False False  True]]
 >>  [[0. 1. 1. 1. 1. 1.]
 [1. 0. 1. 1. 1. 1.]
 [1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 0. 1. 1.]
 [1. 1. 1. 1. 0. 1.]
 [1. 1. 1. 1. 1. 0.]]


In [ ]:
A = np.array([ [1, 2, 3], [2, 2, 2], [3, 3, 3] ])
B = np.array([ [3, 2, 1], [1, 2, 3], [-1, -2, -3] ])
print(f"Маємо два масиви:\n {A} \n {B}")

R = A * B
print(f"Тут виконується поелементне множення:\n {R}")

R = np.dot(A, B)
print(f"Тут, масиви перемножуються як матриці:\n {R}")

і

R = MA * MB

print(f"Тут масиви перетворені на матриці і далі перемножуються:\n {R}")

Маємо два масиви:
 [[1 2 3]
 [2 2 2]
 [3 3 3]] 
 [[ 3  2  1]
 [ 1  2  3]
 [-1 -2 -3]]
Тут виконується поелементне множення:
 [[ 3  4  3]
 [ 2  4  6]
 [-3 -6 -9]]
Тут, масиви перемножуються як матриці:
 [[ 2  0 -2]
 [ 6  4  2]
 [ 9  6  3]]
Тут масиви перетворені на матриці і далі перемножуються:
 [[ 2  0 -2]
 [ 6  4  2]
 [ 9  6  3]]


In [35]:
A = np.array([ [11, 12, 13], [21, 22, 23], [31, 32, 33] ])
B = np.array([1, 2, 3])
C = B[:, np.newaxis]

print(f"Вектор В є рядком {B.shape}: {B} тому додавання буде по рядках:\n {A + B}")

print(f"""Вектор C є стовпцем {C.shape}:
{C}
тому додавання буде по стовпцям:
{A + C}""")

print(f"У випадку додавання рядка до стовпця буде матриця в якої доповнюються рядки і стовпці:\n {B + C}")

Вектор В є рядком (3,): [1 2 3] тому додавання буде по рядках:
 [[12 14 16]
 [22 24 26]
 [32 34 36]]
Вектор C є стовпцем (3, 1):
[[1]
 [2]
 [3]]
тому додавання буде по стовпцям:
[[12 13 14]
 [23 24 25]
 [34 35 36]]
У випадку додавання рядка до стовпця буде матриця в якої доповнюються рядки і стовпці:
 [[2 3 4]
 [3 4 5]
 [4 5 6]]


In [36]:
A = np.array([ [11, 12, 13], [21, 22, 23], [31, 32, 33] ])
B = np.array([1, 2, 3])
C = B[:, np.newaxis]

print(f"Вектор В є рядком {B.shape}: {B} тому додавання буде по рядках:\n {A + B}")

print(f"""Вектор C є стовпцем {C.shape}:
{C}
тому додавання буде по стовпцям:
{A + C}""")

print(f"У випадку додавання рядка до стовпця буде матриця в якої доповнюються рядки і стовпці:\n {B + C}")

Вектор В є рядком (3,): [1 2 3] тому додавання буде по рядках:
 [[12 14 16]
 [22 24 26]
 [32 34 36]]
Вектор C є стовпцем (3, 1):
[[1]
 [2]
 [3]]
тому додавання буде по стовпцям:
[[12 13 14]
 [23 24 25]
 [34 35 36]]
У випадку додавання рядка до стовпця буде матриця в якої доповнюються рядки і стовпці:
 [[2 3 4]
 [3 4 5]
 [4 5 6]]


In [ ]:
D = np.ones(3)
Z = np.zeros((3,1))
print(f"""
При конкатенації рядків маємо: {np.concatenate((D, D))}")
При конкатенації стовпців маємо:\n{np.concatenate((Z, Z))}
Масив D {D} має розмірність {D.shape} тому може виконати операцію конкатенації з В {B} розмірністю {B.shape}:
{np.concatenate((B, D))}
Для конкатенації з С
{C}
де С має розмірність = {C.shape} потрібно змінити розмірність D = {D.shape}
Це можна ось так:
{D[:, np.newaxis].shape}
або
{D.reshape((3,1)).shape}
в результаті ми можем виконати конкатенацію:
{np.concatenate((C, D.reshape((3,1))))}
При повторенні D {D} 2 рази для рядкі та 3 для стовпців будем мати:
{np.tile(D, (2, 3))}
Як бачимо конкатенація та повторення є дещо схожими у деяких випадках:
- конкатенація: {np.concatenate((D, D))}
- повторення: {np.tile(D, 2)}
Також можна перетворити двовимірний масив A розмірністю {A.shape} на рядок: {A.flatten()} з розмірністю {A.flatten().shape}
""")



In [38]:
A = np.arange(1, 10).reshape(3, 3)
homework(f"Original 2D array created with arange:\n{A}")

B = np.ones((3, 3))
rows = np.concatenate((A, B), axis=0)
cols = np.concatenate((A, B), axis=1)
homework(f"Concatenation along rows:\n{rows}")
homework(f"Concatenation along columns:\n{cols}")

rep = np.tile(A, (2, 2))
homework(f"Repeated array:\n{rep}")
C = np.arange(6).reshape(3, 2)  
homework(f"Array with different dimensions:\n{C}")
W = np.concatenate((A, C), axis=1)
homework(f"Adjusted concatenation after reshaping:\n{W}")


A1D = np.arange(12)
options = [(1, 12), (12, 1), (2, 6), (6, 2), (3, 4), (4, 3)]
reshaped_lists = [A1D.reshape(shape) for shape in options]
homework("All possible reshape combinations:")
for shape in options:
    reshaped = A1D.reshape(shape)
    homework(f"Shape {shape}:\n{reshaped}\n")


 >>  Original 2D array created with arange:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
 >>  Concatenation along rows:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
 >>  Concatenation along columns:
[[1. 2. 3. 1. 1. 1.]
 [4. 5. 6. 1. 1. 1.]
 [7. 8. 9. 1. 1. 1.]]
 >>  Repeated array:
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]
 [1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]]
 >>  Array with different dimensions:
[[0 1]
 [2 3]
 [4 5]]
 >>  Adjusted concatenation after reshaping:
[[1 2 3 0 1]
 [4 5 6 2 3]
 [7 8 9 4 5]]
 >>  All possible reshape combinations:
 >>  Shape (1, 12):
[[ 0  1  2  3  4  5  6  7  8  9 10 11]]

 >>  Shape (12, 1):
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]

 >>  Shape (2, 6):
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

 >>  Shape (6, 2):
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]

 >>  Shape (3, 4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 >>  Shape (4, 3):
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

